# Generated by Django 6.0 on 2026-01-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Artikelname')),
                ('menge', models.IntegerField(default=0, verbose_name='Bestand')),
                ('standort', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lagerort')),
                ('artikelnummer', models.CharField(max_length=50, unique=True, verbose_name='Artikel-Nr.')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikelbestand',
                'db_table': 'artikel',
                'ordering': ['-id'],
            },
        ),
    ]
