# Generated by Django 6.0.1 on 2026-01-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Milijan Davidovic', max_length=100)),
                ('titel', models.CharField(default='Junior Python Developer', max_length=100)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('standort', models.CharField(default='Kempten / Gera', max_length=100)),
                ('skills', models.TextField(help_text='Kommagetrennte Liste, Python, Django, FastAPI')),
            ],
            options={
                'verbose_name': 'Mein Profil',
                'verbose_name_plural': 'Mein Profil',
            },
        ),
    ]
