# Generated by Django 6.0.1 on 2026-01-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventar_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name='Über mich'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub Link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn Link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(help_text='Gib deine Skills mit Komma getrennt ein, z.B. Python, Django, FastAPI', verbose_name='Tech Stack'),
        ),
    ]
